FROM centos:7
LABEL org.opencontainers.image.authors="eubnara@gmail.com"

ENV LC_ALL en_US.utf8
RUN yum -y install python3-devel.x86_64 && \
    pip3 install --upgrade pip && \
    pip3 install --user ansible
ENV PATH "$PATH:/root/.local/bin"

COPY common/ansible /root/ansible
RUN ansible-playbook /root/ansible/init_apacheds.yml

COPY common/script/apacheds_entrypoint.sh /opt/apacheds_entrypoint.sh
CMD ["bash", "/opt/apacheds_entrypoint.sh"]
