FROM centos:7
LABEL org.opencontainers.image.authors="eubnara@gmail.com"

ENV LC_ALL en_US.utf8
RUN yum -y install python3-devel.x86_64 && \
    pip3 install --upgrade pip && \
    pip3 install --user ansible
ENV PATH "$PATH:/root/.local/bin"

COPY files/rpm /root/rpm
COPY files/ansible /root/ansible
COPY files/script /root/script
COPY files/lib /root/lib

RUN ansible-playbook /root/ansible/init_ambari_server.yml

CMD [ "bash", "/root/script/ambari_server_entrypoint.sh" ]
