FROM centos:7
LABEL org.opencontainers.image.authors="eubnara@gmail.com"

ENV LC_ALL en_US.utf8
RUN yum -y install python3-devel.x86_64 && \
    pip3 install --upgrade pip && \
    pip3 install --user ansible
ENV PATH "$PATH:/root/.local/bin"

# COPY common/rpm /root/rpm
COPY common/ansible /root/ansible
COPY common/script /root/script

RUN ansible-playbook /root/ansible/init_ambari_agent.yml

CMD [ "bash", "/root/script/ambari_agent_entrypoint.sh" ]
