---

- name: install necessary or useful packages
  ansible.builtin.yum:
    name:
      - java-1.8.0-openjdk-devel.x86_64
      - curl
      - less
      - vim
      - openssh-clients
    state: present
